---
svkms_setup_admin_username: "admin"

svkms_setup_default_policies:
  - name: "default-rotation-policy"
    rules:
      - principal: "*"
        actions: ["encrypt", "decrypt", "rotate"]
        resources: ["*"]
  - name: "high-security-policy"
    rules:
      - principal: "*"
        actions: ["encrypt", "decrypt"]
        resources: ["*"]

svkms_setup_ca_common_name: "StorMagic SvKMS Root CA"
