---
svkms_setup_admin_username: "admin"

svkms_setup_default_policies:
  - name: "default-rotation-policy"
    rules:
      - effect: allow
        operations: ["encrypt", "decrypt", "rotate"]
        algorithm: AES
        min_key_length: 256
  - name: "high-security-policy"
    rules:
      - effect: allow
        operations: ["encrypt", "decrypt"]
        algorithm: AES
        min_key_length: 256

svkms_setup_ca_common_name: "StorMagic SvKMS Root CA"
