---
version: 3

images:
  base_image:
    name: quay.io/ansible/ansible-runner:latest

dependencies:
  galaxy: requirements.yml
  python:
    - pywinrm>=0.4.0
    - pyvmomi>=8.0.0
  system: bindep.txt
