---
svsan_patching_postflight_checks:
  - connectivity
  - targets
  - mirrors
svsan_patching_postflight_mirror_sync_threshold: 100
svsan_patching_postflight_windows_mgmt_host: "{{ groups['windows_mgmt'][0] | default(omit) }}"
