---
svsan_preflight_checks:
  - connectivity
  - license
  - targets
  - mirrors
  - pools

svsan_mirror_sync_threshold: 100
svsan_pool_capacity_warn_pct: 80
svsan_min_datastore_paths: 2
svsan_windows_mgmt_host: "{{ groups['windows_mgmt'][0] | default(omit) }}"
