---
galaxy_info:
  role_name: svsan_patching_postflight
  author: StorMagic Ltd
  description: Post-patching verification for StorMagic SvSAN
  license: GPL-3.0-or-later
  min_ansible_version: "2.16"
  platforms:
    - name: Windows
      versions:
        - all
dependencies: []
