---
- name: Rotate SvKMS Encryption Keys
  hosts: localhost
  gather_facts: false
  vars:
    svkms_host: "{{ vault_svkms_host }}"
    svkms_api_key: "{{ vault_svkms_api_key }}"
  tasks:
    - name: Rotate the application encryption key
      xianganwu.stormagic.svkms_key:
        host: "{{ svkms_host }}"
        api_key: "{{ svkms_api_key }}"
        name: app-encryption-key
        state: rotated
